### ISSUE TITLE
Background photo 

### ISSUE THREAD

**Issue by xyluz** [governmentClout/WEB#54]
![capture](https://user-images.githubusercontent.com/13081285/52091427-b3a84080-25b4-11e9-9b8c-9b12a8e9c68d.PNG)

Check this display, I think you are printing out the profile photo as background

**Comment by oluwabukolatina** [comment]
please, also add the urls of the page you are sending issues for

**Comment by oluwabukolatina** [comment]
fixed

**Comment by xyluz** [comment]
@oluwabukolatina No, it's not fixed. 

![capture](https://user-images.githubusercontent.com/13081285/52167591-c5f1be00-271d-11e9-806b-83511d0542d1.PNG)
